if(window.matchMedia("(display-mode: standalone)").matches||navigator.standalone===true)location.replace("./app.html");

const shareUrl="https://drinks.hizach.com/";
const shareData={title:"Cabin Drinks",text:"An offline-friendly food and beverage service pad for flight crews.",url:shareUrl};
const shareButton=document.querySelector("#shareButton");

const shareSheet=document.createElement("div");
shareSheet.className="share-sheet";
shareSheet.hidden=true;
shareSheet.innerHTML=`
  <button class="share-backdrop" type="button" aria-label="Close sharing options"></button>
  <section class="share-panel" role="dialog" aria-modal="true" aria-labelledby="shareTitle">
    <button class="share-close" type="button" aria-label="Close">×</button>
    <img class="share-app-icon" src="./app-icon.svg" alt="">
    <p class="eyebrow">Share Cabin Drinks</p>
    <h2 id="shareTitle">Help another crew member get started.</h2>
    <p class="share-intro">Share the link, copy it, or let someone scan the QR code directly from your phone.</p>
    <div class="share-actions"><button id="nativeShareButton" class="primary" type="button">Share Link</button><button id="copyShareButton" class="copy-link-button" type="button">Copy Link</button></div>
    <div class="qr-card"><div class="qr-code-wrap"><img id="shareQrCode" class="qr-code" alt="QR code for Cabin Drinks" crossorigin="anonymous"><span class="qr-logo"><img src="./app-icon.svg" alt="" crossorigin="anonymous"></span></div><strong>Scan to open Cabin Drinks</strong><span>drinks.hizach.com</span><div class="qr-actions"><button id="saveQrButton" type="button">Save QR Code</button><button id="shareQrButton" type="button">Share QR Image</button></div><small id="qrActionStatus" class="qr-action-status" role="status" aria-live="polite"></small></div>
  </section>`;
document.body.appendChild(shareSheet);
const qrImage=shareSheet.querySelector("#shareQrCode");
qrImage.src=`https://api.qrserver.com/v1/create-qr-code/?size=900x900&ecc=H&margin=22&data=${encodeURIComponent(shareUrl)}`;
const closeShare=()=>{shareSheet.classList.remove("is-open");setTimeout(()=>{shareSheet.hidden=true},180);document.body.style.overflow=""};
const openShare=()=>{shareSheet.hidden=false;document.body.style.overflow="hidden";requestAnimationFrame(()=>shareSheet.classList.add("is-open"))};
shareButton?.addEventListener("click",openShare);
shareSheet.querySelector(".share-backdrop")?.addEventListener("click",closeShare);
shareSheet.querySelector(".share-close")?.addEventListener("click",closeShare);
shareSheet.querySelector("#nativeShareButton")?.addEventListener("click",async()=>{if(navigator.share){try{await navigator.share(shareData)}catch{}}else{await navigator.clipboard.writeText(shareUrl);alert("Link copied")}});
shareSheet.querySelector("#copyShareButton")?.addEventListener("click",async event=>{await navigator.clipboard.writeText(shareUrl);const button=event.currentTarget;const original=button.textContent;button.textContent="Copied ✓";button.classList.add("copied");setTimeout(()=>{button.textContent=original;button.classList.remove("copied")},1800)});
document.addEventListener("keydown",event=>{if(event.key==="Escape"&&!shareSheet.hidden)closeShare()});
const qrStatus=shareSheet.querySelector("#qrActionStatus");
const setQrStatus=message=>{qrStatus.textContent=message;setTimeout(()=>{if(qrStatus.textContent===message)qrStatus.textContent=""},2600)};
const loadImage=src=>new Promise((resolve,reject)=>{const image=new Image();image.crossOrigin="anonymous";image.onload=()=>resolve(image);image.onerror=reject;image.src=src});
const buildQrFile=async()=>{const [qr,icon]=await Promise.all([loadImage(qrImage.src),loadImage(new URL("./app-icon.svg",location.href).href)]);const canvas=document.createElement("canvas");canvas.width=1080;canvas.height=1320;const ctx=canvas.getContext("2d");ctx.fillStyle="#f7f4ee";ctx.fillRect(0,0,canvas.width,canvas.height);ctx.fillStyle="#202423";ctx.textAlign="center";ctx.font="700 58px system-ui,-apple-system,sans-serif";ctx.fillText("Cabin Drinks",540,90);ctx.font="400 30px system-ui,-apple-system,sans-serif";ctx.fillStyle="#626865";ctx.fillText("Scan to open the offline service pad",540,140);const qrSize=850,qrX=(canvas.width-qrSize)/2,qrY=190;ctx.fillStyle="#fff";ctx.beginPath();ctx.roundRect(qrX-24,qrY-24,qrSize+48,qrSize+48,36);ctx.fill();ctx.drawImage(qr,qrX,qrY,qrSize,qrSize);const iconSize=175,iconX=(canvas.width-iconSize)/2,iconY=qrY+(qrSize-iconSize)/2;ctx.fillStyle="#fff";ctx.beginPath();ctx.roundRect(iconX-18,iconY-18,iconSize+36,iconSize+36,34);ctx.fill();ctx.drawImage(icon,iconX,iconY,iconSize,iconSize);ctx.fillStyle="#202423";ctx.font="700 38px system-ui,-apple-system,sans-serif";ctx.fillText("drinks.hizach.com",540,1135);ctx.font="500 27px system-ui,-apple-system,sans-serif";ctx.fillStyle="#626865";ctx.fillText("Free · Private · Ready for airplane mode",540,1190);const blob=await new Promise(resolve=>canvas.toBlob(resolve,"image/png",1));return new File([blob],"cabin-drinks-qr.png",{type:"image/png"})};
shareSheet.querySelector("#saveQrButton")?.addEventListener("click",async()=>{try{const file=await buildQrFile();const link=document.createElement("a");link.href=URL.createObjectURL(file);link.download=file.name;link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000);setQrStatus("QR code saved ✓")}catch{setQrStatus("Couldn’t save the image. Try Share QR Image.")}});
shareSheet.querySelector("#shareQrButton")?.addEventListener("click",async()=>{try{const file=await buildQrFile();if(navigator.canShare?.({files:[file]})){await navigator.share({title:"Cabin Drinks",text:"Scan to open Cabin Drinks",files:[file]})}else{const link=document.createElement("a");link.href=URL.createObjectURL(file);link.download=file.name;link.click();setQrStatus("QR image downloaded ✓")}}catch{setQrStatus("Couldn’t share the QR image.")}});

const bugUrl="https://github.com/zachfranzen123/cabin-drinks/issues/new?template=bug_report.yml";
const featureUrl="https://github.com/zachfranzen123/cabin-drinks/issues/new?template=feature_request.yml";
const issuesUrl="https://github.com/zachfranzen123/cabin-drinks/issues";
const navActions=document.querySelector(".nav-actions");
if(navActions&&!navActions.querySelector(".bug-nav-link")){const bugLink=document.createElement("a");bugLink.className="bug-nav-link";bugLink.href=bugUrl;bugLink.target="_blank";bugLink.rel="noopener noreferrer";bugLink.textContent="Report a Bug";navActions.insertBefore(bugLink,shareButton)}
const feedbackSection=document.querySelector(".feedback");
if(feedbackSection)feedbackSection.innerHTML=`<div class="feedback-intro"><p class="eyebrow">Help improve it</p><h2>Found something—or have an idea?</h2><p>Cabin Drinks gets better through crew feedback. Choose an option below to send a structured report through GitHub.</p><p class="feedback-privacy"><strong>Please don’t include passenger names, flight numbers, or other private information.</strong></p><a class="feedback-email" href="mailto:zach@hizach.com">Prefer email? zach@hizach.com</a></div><div class="github-feedback-actions" aria-label="Cabin Drinks feedback options"><a class="github-feedback-card" href="${bugUrl}" target="_blank" rel="noopener noreferrer"><span class="github-feedback-icon">🐞</span><span><strong>Report a Bug</strong><small>Tell me what broke, what device you used, and how to reproduce it.</small></span><i>↗</i></a><a class="github-feedback-card" href="${featureUrl}" target="_blank" rel="noopener noreferrer"><span class="github-feedback-icon">💡</span><span><strong>Suggest a Feature</strong><small>Share an idea that could make inflight service easier.</small></span><i>↗</i></a><a class="github-feedback-card" href="${issuesUrl}" target="_blank" rel="noopener noreferrer"><span class="github-feedback-icon">📋</span><span><strong>View Feedback & Progress</strong><small>See open reports, requests, and completed improvements.</small></span><i>↗</i></a></div>`;

const guide=document.querySelector(".guide");
if(guide){
  guide.innerHTML=`<div class="flow-heading"><p class="eyebrow">How it works</p><h2>From order to delivery.</h2><p>No pretend screens—just the actual service flow Cabin Drinks supports.</p></div><div class="service-flow" role="list"><article class="flow-step active" role="listitem" data-step="0"><span class="flow-number">01</span><span class="flow-icon">💺</span><div><strong>Tap the seat</strong><small>Choose the passenger’s seat as you walk the cabin.</small></div></article><span class="flow-arrow" aria-hidden="true">→</span><article class="flow-step" role="listitem" data-step="1"><span class="flow-number">02</span><span class="flow-icon">🥤</span><div><strong>Add the order</strong><small>Select drinks, food, quantities, and modifiers.</small></div></article><span class="flow-arrow" aria-hidden="true">→</span><article class="flow-step" role="listitem" data-step="2"><span class="flow-number">03</span><span class="flow-icon">🧾</span><div><strong>Prepare in the galley</strong><small>Use grouped totals and seat-by-seat instructions.</small></div></article><span class="flow-arrow" aria-hidden="true">→</span><article class="flow-step" role="listitem" data-step="3"><span class="flow-number">04</span><span class="flow-icon">✓</span><div><strong>Deliver and clear</strong><small>Confirm each order once it reaches the passenger.</small></div></article></div><div class="flow-progress" aria-hidden="true"><span></span></div>`;
  const steps=[...guide.querySelectorAll(".flow-step")];let current=0,timer;
  const show=index=>{current=index;steps.forEach((step,i)=>step.classList.toggle("active",i===index));guide.style.setProperty("--flow-progress",`${(index+1)*25}%`)};
  const start=()=>{clearInterval(timer);timer=setInterval(()=>show((current+1)%steps.length),2200)};
  steps.forEach((step,index)=>step.addEventListener("click",()=>{show(index);start()}));
  show(0);if(!window.matchMedia("(prefers-reduced-motion: reduce)").matches)start();
}

const style=document.createElement("style");
style.textContent=`
.bug-nav-link{display:inline-flex;align-items:center;min-height:38px;padding:0 14px;border-radius:999px;background:#e85d3f;color:#fff!important;font-weight:800;text-decoration:none;white-space:nowrap}.feedback-email{display:inline-block;margin-top:.6rem;font-weight:700}.feedback-privacy{margin-top:1rem;font-size:.82rem;line-height:1.45;opacity:.78}.github-feedback-actions{display:grid;gap:.8rem}.github-feedback-card{display:grid;grid-template-columns:auto 1fr auto;gap:.85rem;align-items:center;padding:1rem;border:1px solid rgba(255,255,255,.16);border-radius:18px;background:rgba(255,255,255,.07);color:inherit;text-decoration:none}.github-feedback-card strong,.github-feedback-card small{display:block}.github-feedback-card small{margin-top:.2rem;opacity:.76}.github-feedback-icon{font-size:1.3rem}.github-feedback-card i{font-style:normal}
.share-sheet[hidden]{display:none}.share-sheet{position:fixed;inset:0;z-index:1000;display:grid;align-items:end}.share-backdrop{position:absolute;inset:0;border:0;background:rgba(0,0,0,.68);backdrop-filter:blur(7px)}.share-panel{position:relative;width:min(100%,560px);max-height:92vh;margin:0 auto;padding:28px 22px calc(24px + env(safe-area-inset-bottom));overflow:auto;border-radius:28px 28px 0 0;background:#f7f4ee;color:#202423;text-align:center;transform:translateY(28px);opacity:.4;transition:.22s}.share-sheet.is-open .share-panel{transform:none;opacity:1}.share-close{position:absolute;top:14px;right:16px;width:38px;height:38px;border:0;border-radius:50%}.share-app-icon{width:62px;height:62px}.share-actions,.qr-actions{display:grid;grid-template-columns:1fr 1fr;gap:10px}.copy-link-button,.qr-actions button{min-height:48px;border:1px solid #b7bcb9;border-radius:13px;background:#fff;color:#202423;font-weight:800}.qr-card{margin-top:18px;padding:18px;border:1px solid #ddd;border-radius:22px;background:#fff}.qr-code-wrap{position:relative;width:min(72vw,290px);aspect-ratio:1;margin:0 auto 14px}.qr-code{width:100%}.qr-logo{position:absolute;left:50%;top:50%;width:21%;transform:translate(-50%,-50%);padding:7px;border-radius:22%;background:#fff}.qr-logo img{width:100%}.qr-card strong,.qr-card>span{display:block}.qr-actions{margin-top:16px}
.guide{--flow-progress:25%;max-width:none!important;padding:92px max(22px,calc((100vw - 1120px)/2))!important;background:#202423;color:#fff}.flow-heading{max-width:680px}.flow-heading h2{margin:0;font-size:clamp(40px,6vw,66px);line-height:.98;letter-spacing:-.055em}.flow-heading>p:last-child{margin:18px 0 0;color:#b8c0bc;font-size:17px}.service-flow{margin-top:48px;display:grid;grid-template-columns:1fr auto 1fr auto 1fr auto 1fr;gap:12px;align-items:stretch}.flow-step{position:relative;min-height:230px;padding:22px;display:flex;flex-direction:column;border:1px solid rgba(255,255,255,.13);border-radius:22px;background:rgba(255,255,255,.045);transition:transform .35s ease,border-color .35s ease,background .35s ease;cursor:pointer}.flow-step.active{transform:translateY(-8px);border-color:#69c7bd;background:rgba(105,199,189,.14)}.flow-number{color:#69c7bd;font-size:12px;font-weight:900;letter-spacing:.12em}.flow-icon{margin:24px 0 28px;font-size:42px;line-height:1}.flow-step strong,.flow-step small{display:block}.flow-step strong{font-size:18px}.flow-step small{margin-top:7px;color:#afb8b3;line-height:1.45}.flow-arrow{align-self:center;color:#69c7bd;font-size:28px;transition:transform .35s ease}.flow-step.active+.flow-arrow{transform:translateX(5px)}.flow-progress{height:3px;margin-top:28px;border-radius:999px;background:rgba(255,255,255,.12);overflow:hidden}.flow-progress span{display:block;width:var(--flow-progress);height:100%;background:#69c7bd;transition:width .45s ease}
@media(max-width:800px){.history-link{display:none}.service-flow{grid-template-columns:1fr}.flow-arrow{transform:rotate(90deg)}.flow-step.active+.flow-arrow{transform:rotate(90deg) translateX(5px)}.flow-step{min-height:0;display:grid;grid-template-columns:42px 48px 1fr;gap:12px;align-items:center}.flow-icon{margin:0;font-size:32px}.flow-number{align-self:start}.flow-step.active{transform:translateX(6px)}.guide{padding:72px 20px!important}.share-actions,.qr-actions{grid-template-columns:1fr}}
@media(prefers-reduced-motion:reduce){.flow-step,.flow-arrow,.flow-progress span,.share-panel{transition:none!important}}
`;
document.head.appendChild(style);
const currentVersion=document.querySelector(".current-version");if(currentVersion)currentVersion.textContent="Version 14 · Current";
const version12=[...document.querySelectorAll(".release")].find(item=>item.querySelector("b")?.textContent.trim()==="Version 12");if(version12){version12.open=false;const label=version12.querySelector("em");if(label)label.textContent="July 2026"}